### ISSUE TITLE
[FEATURE] Add revert-commit.yml workflow to revert a commit using git revert  Body:

### ISSUE THREAD

**Issue by guibranco** [guibranco/gstraccini-bot-workflows#98]
This workflow will run when triggered by the bot service, and will revert a given commit on a specified branch. It's used to programmatically undo a problematic change via GitHub Actions.

```yml
name: Revert Commit

on:
  workflow_dispatch:
    inputs:
      owner:
        description: "The owner of the repository"
        required: true
      repository:
        description: "The repository name"
        required: true
      branch:
        description: "The branch to revert on"
        required: true
      sha1:
        description: "The commit SHA to revert"
        required: true
      installationId:
        description: "GitHub App installation ID"
        required: true
      checkRunId:
        description: "Check run ID"
        required: true
      pull_request:
        description: "PR number (for comment feedback)"
        required: true

permissions:
  contents: write
  pull-requests: write
  checks: write

env:
  GHA_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ github.event.inputs.installationId }}

      - name: Mark check run as in_progress
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repository }}
          check_id: ${{ github.event.inputs.checkRunId }}
          status: in_progress
          details_url: ${{ env.GHA_URL }}

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: "${{ github.event.inputs.owner }}/${{ github.event.inputs.repository }}"
          ref: ${{ github.event.inputs.branch }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Configure Git identity
        run: |
          git config --local user.email "150967461+gstraccini[bot]@users.noreply.github.com"
          git config --local user.name "gstraccini[bot]"

      - name: Revert the commit
        run: |
          git revert --no-edit ${{ github.event.inputs.sha1 }}
          git push origin ${{ github.event.inputs.branch }}

      - name: Comment PR with revert result
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          repo-owner: ${{ github.event.inputs.owner }}
          repo-name: ${{ github.event.inputs.repository }}
          issue: ${{ github.event.inputs.pull_request }}
          message: |
            :rewind: [Revert Commit](${{ env.GHA_URL }}) succeeded.
            The commit `${{ github.event.inputs.sha1 }}` was reverted on branch `${{ github.event.inputs.branch }}`.

      - name: Mark check run as success
        if: success()
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repository }}
          check_id: ${{ github.event.inputs.checkRunId }}
          conclusion: success
          details_url: ${{ env.GHA_URL }}
          output: |
            {"title": "Commit reverted ✅", "summary": "Commit ${{ github.event.inputs.sha1 }} has been reverted."}

      - name: Mark check run as failure
        if: failure()
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repository }}
          check_id: ${{ github.event.inputs.checkRunId }}
          conclusion: failure
          details_url: ${{ env.GHA_URL }}
          output: |
            {"title": "Revert failed ❌", "summary": "See logs for error details."}
```

### Acceptance Criteria

* [ ] Workflow can be triggered with required inputs.
* [ ] Reverts the specified commit and pushes it.
* [ ] Adds a comment to the related PR with success/failure message.
* [ ] Updates check run with appropriate status.
